base:
  template:
    - settings
    - tilt
    - extra_styles
  variables:
    state_on: >
      [[[ return ['on', 'On', 'home', 'cool', 'heat', 'fan_only', 'playing', 'unlocked'].indexOf(!entity || entity.state) !== -1; ]]]
    state: >
      [[[ return !entity || entity.state; ]]]
    entity_id: >
      [[[ return !entity || entity.entity_id; ]]]
    entity_picture: >
      [[[ return !entity || entity.attributes.entity_picture; ]]]
    timeout: >
      [[[ return !entity || Date.now() - Date.parse(entity.last_changed); ]]]
  aspect_ratio: 1/1
  show_state: true
  show_icon: false
  state_display: >
    [[[ 
      const stateDict = {
        'on': variables.translate_on,
        'off': variables.translate_off,
        'On': variables.translate_on,
        'Off': variables.translate_off,
        'cool': variables.translate_cool,
        'heat': variables.translate_heat,
        'fan_only': variables.translate_fan_only,
      };
      if (variables.state === true) return variables.translate_unknown;
      return stateDict[variables.state];
    ]]]
  tap_action:
    ui_sound_tablet: |
      [[[ 
        let screensaver = states[variables.entity_tablet] === undefined ||
            states[variables.entity_tablet].state;

        if (variables.state === 'off' && screensaver === 'off') {
            hass.callService('media_player', 'play_media', {
                entity_id: variables.entity_browser_mod,
                media_content_id: '/local/sound/on.m4a',
                media_content_type: 'music'
            });
        }
        if (variables.state_on && screensaver === 'off') {
            hass.callService('media_player', 'play_media', {
                entity_id: variables.entity_browser_mod,
                media_content_id: '/local/sound/off.m4a',
                media_content_type: 'music'
            });
        }
      ]]]
    card_bounce: |
      [[[ 
        if (this.getElementsByTagName("style").length === 0) {
            let mq = window.matchMedia('(max-width: 800px)').matches;
            let style = document.createElement('style');
            style.innerHTML = `
                @keyframes card_bounce {
                    0%   { transform: scale(1); }
                    10%  { transform: scale(${ mq ? '0.92' : '0.94' }); }
                    25%  { transform: scale(1); }
                    30%  { transform: scale(${ mq ? '0.96' : '0.98' }); }
                    100% { transform: scale(1); }
                }
            `;
            this.appendChild(style);
        }
        let duration = 800;
        this.style.animation = \`card_bounce \${duration}ms cubic-bezier(0.22, 1, 0.36, 1)\`;
        window.setTimeout(() => { this.style.animation = "none"; }, duration + 100);
      ]]]
    action: toggle
    haptic: medium
  double_tap_action:
    haptic: success
  hold_action:
    action: block
  styles:
    card:
      - border-radius: var(--button-card-border-radius)
      - border-width: 0
      - -webkit-tap-highlight-color: rgba(0,0,0,0)
      - transition: none
      - height: auto
      - padding: 8px
      - font-size: 14px
      - --mdc-ripple-color: >
          [[[ return variables.state_on ? 'rgb(0, 0, 0)' : '#97989c'; ]]]
      - color: >
          [[[ return variables.state_on ? '#4b5254' : '#97989c'; ]]]
      - background-color: >
          [[[ return variables.state_on ? 'rgba(255, 255, 255, 0.85)' : 'rgba(115, 115, 115, 0.25)'; ]]]
