settings:
  variables:
    entity_tablet: switch.galaxy_tab_a_screensaver
    entity_browser_mod: media_player.88b28897_06c0391e

    translate_unknown: Unknown
    translate_idle: Idle
    translate_home: Home
    translate_not_home: Away
    translate_available: Available
    translate_no_updates: No Updates
    translate_update_available: Update available
    translate_updates_available: Updates available

    translate_on: On
    translate_off: Off
    translate_cool: Cool
    translate_fan_only: Fan Only
    translate_playing: Playing
    translate_paused: Pausad
    translate_standby: Standby
