- id: '1672140546661'
  alias: GitHub Push
  description: Everyday in 4AM will update the github.
  trigger:
  - platform: time
    at: 04:00:00
  condition: []
  action:
  - service: shell_command.pushupdates_to_github
    data: {}
  - service: notify.supervisor_telegram
    data:
      message: "\U0001F916 Automation - GitHub Push"
  mode: single
- id: '1672416137952'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      time: '19:00:00'
      exclude:
        entity_id:
        - sensor.elians_iphone_battery_level
        - sensor.ofir_phone_battery_level
      actions:
      - service: notify.supervisor_telegram
        data:
          message: "\U0001F916 Automation - {{sensors}} has low on battery, please
            replace it."
- id: '1672558313040'
  alias: Laundry Machine has started
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.laundry_machine_power
    for:
      hours: 0
      minutes: 0
      seconds: 12
    above: 10
  condition:
  - condition: state
    entity_id: input_select.washing_machine_status
    state: 'Off'
  action:
  - service: input_select.select_option
    data:
      option: 'On'
    target:
      entity_id: input_select.washing_machine_status
  - service: notify.home_assistant_group
    data:
      message: "\U0001F456 Laundry machine has started!"
  mode: single
- id: '1672558877974'
  alias: Laundry machine has finished
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.laundry_machine_power
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: 5
  condition:
  - condition: state
    entity_id: input_select.washing_machine_status
    state: 'On'
  action:
  - service: input_select.select_option
    data:
      option: 'Off'
    target:
      entity_id: input_select.washing_machine_status
  - service: notify.home_assistant_group
    data:
      message: "\U0001F456 Laundry machine has finished!"
  mode: single
- id: '1672597703705'
  alias: Water Leakage Kitchen Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak_sensor_kitchen_sink_water_leak
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.notify
    data:
      message: ⚠️ Water Leak has been detected in Kitchen ⚠️
  - service: notify.home_assistant_group
    data:
      message: ⚠️ Water Leak has been detected in Kitchen ⚠️
  mode: single
- id: '1672688044345'
  alias: Water Leakage Bathroom Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak_sensor_bathroom_sink_water_leak
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.notify
    data:
      message: ⚠️ Water Leak has been detected in Bathroom ⚠️
  - service: notify.home_assistant_group
    data:
      message: ⚠️ Water Leak has been detected in Bathroom ⚠️
  mode: single
- id: '1672692110951'
  alias: Switcher Boiler On Notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.switcher_v4_yair_stern_power_consumption
    for:
      hours: 0
      minutes: 0
      seconds: 3
    above: 5
  condition:
  - condition: state
    entity_id: input_select.switcher_boiler_status
    state: 'Off'
  action:
  - service: input_select.select_option
    data:
      option: 'On'
    target:
      entity_id: input_select.switcher_boiler_status
  - service: notify.home_assistant_group
    data:
      message: "\U0001F6BF Switcher device has been turned ON "
  mode: single
- id: '1672692174596'
  alias: Switcher Boiler Off Notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.switcher_v4_yair_stern_power_consumption
    for:
      hours: 0
      minutes: 0
      seconds: 15
    below: 5
  condition:
  - condition: state
    entity_id: input_select.switcher_boiler_status
    state: 'On'
  action:
  - service: input_select.select_option
    data:
      option: 'Off'
    target:
      entity_id: input_select.switcher_boiler_status
  - service: notify.home_assistant_group
    data:
      message: "\U0001F6BF Switcher device has been turned OFF"
  mode: single
- id: '1673469552878'
  alias: 'Helper: Set Bedroom AC Status to On'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ac_bedroom_power
    for:
      hours: 0
      minutes: 1
      seconds: 0
    above: 5
  condition:
  - condition: state
    entity_id: input_select.bedroom_ac_status
    state: 'Off'
  action:
  - service: input_select.select_option
    data:
      option: 'On'
    target:
      entity_id: input_select.bedroom_ac_status
  - service: notify.supervisor_telegram
    data:
      message: "\U0001F916 Automation - Bedroom AC Status has been changed to On!"
  mode: single
- id: '1673469610479'
  alias: 'Helper: Set Bedroom AC Status to Off'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ac_bedroom_power
    for:
      hours: 0
      minutes: 3
      seconds: 30
    below: 4
  condition:
  - condition: state
    entity_id: input_select.bedroom_ac_status
    state: 'On'
  action:
  - service: input_select.select_option
    data:
      option: 'Off'
    target:
      entity_id: input_select.bedroom_ac_status
  - service: notify.supervisor_telegram
    data:
      message: "\U0001F916 Automation - Bedroom AC Status has been changed to Off!"
  mode: single
- id: '1673808016982'
  alias: Bedroom A/C Bedroom OFF
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
    id: 1:00 am
    alias: At 1:00 am
  - platform: state
    entity_id:
    - input_select.bedroom_ac_status
    to: 'On'
    id: Bedroom A/C turned on
    alias: Bedroom A/C turned on
  - platform: state
    entity_id:
    - input_select.bedroom_ac_status
    to: 'Off'
    id: Bedroom A/C turned off
    alias: Bedroom A/C turned off
  - platform: state
    entity_id:
    - timer.a_c_timer
    to: idle
    id: Timer Finished
    from: active
    alias: Bedroom A/C timer finished/canceled
  condition:
  - condition: time
    before: 05:30:00
    after: 01:00:00
    alias: Time between 1 am & 5 am
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: trigger
          id: 1:00 am
          alias: Triggered at 01:00 am
        - condition: trigger
          id: Bedroom A/C turned on
          alias: Triggered by Bedroom A/C turned on
        alias: Triggered by 1:00 am or Bedroom A/C turned on
      - condition: state
        entity_id: input_select.bedroom_ac_status
        state: 'On'
      sequence:
      - service: timer.start
        data:
          duration: 01:30:00
        alias: Start Bedroom A/C Timer
        target:
          entity_id: timer.a_c_timer
    - conditions:
      - condition: trigger
        id: Bedroom A/C turned off
        alias: Bedroom A/C turned off
      - condition: state
        entity_id: input_select.bedroom_ac_status
        state: 'Off'
      sequence:
      - service: timer.cancel
        data: {}
        alias: Cancel Bedroom A/C Timer
        target:
          entity_id: timer.a_c_timer
    - conditions:
      - condition: trigger
        id: Timer Finished
        alias: Bedroom A/C Timer Finished
      sequence:
      - service: script.ir_turn_off_bedroom_ac
        data: {}
      - service: notify.supervisor_telegram
        data:
          message: "\U0001F916 Automation - Bedroom A/C automation has closed the
            A/C!"
  mode: single
- id: '1674326763431'
  alias: Tag Lights off is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 7efb2f01-320d-4a37-813f-0f6bd3406141
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.living_room_light_module
      - light.xiaomi_yeelink
  - service: script.turn_off_bedroom_light
    data: {}
  - service: notify.supervisor_telegram
    data:
      message: "\U0001F916 Automation - NFC Tag has been scanned!"
  mode: single
- id: '1674400177066'
  alias: Hallway Light Switch Button
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.hallway_sticker_switch_button_action
    to: single
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      device_id: 3e6f5b46bee6ed340dcbc9c7419e4e10
  - service: notify.supervisor_telegram
    data:
      message: "\U0001F916 Automation - Hallway Light Switch Button"
  mode: single
- id: '1675145318623'
  alias: New Item Added to Shopping List
  description: Notification to Telegram Group when new Item has been added to Shopping
    List.
  trigger:
  - platform: event
    event_type: shopping_list_updated
    event_data:
      action: add
  condition: []
  action:
  - service: notify.home_assistant_group
    data:
      message: "\U0001F6D2 {{ trigger.event.data.item.name }}\nhas been added to the
        shopping list.\n"
      data:
        clickAction: /shopping-list
        url: /shopping-list
  mode: single
- id: '1675577078929'
  alias: Supervisor - Main Door Open
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.main_door_sensor_contact
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: device_tracker.ofir_phone
    state: not_home
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 45
  - service: camera.snapshot
    data:
      filename: /config/www/tmp/snapshot_living_room_sub.jpg
    target:
      entity_id: camera.living_room_sub
  - service: telegram_bot.send_photo
    data:
      authentication: digest
      file: /config/www/tmp/snapshot_living_room_sub.jpg
      caption: "\U0001F916 Automation - Main Door is open now!"
  mode: single
- id: '1675577121363'
  alias: Supervisor - Main Door Closed
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.main_door_sensor_contact
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: device_tracker.ofir_phone
    state: not_home
  action:
  - service: notify.supervisor_telegram
    data:
      message: "\U0001F916 Automation - Main Door is closed now!"
  mode: single
- id: '1675577446512'
  alias: Supervisor - Elian is Away
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.elians_iphone
    from: home
    to: not_home
  condition: []
  action:
  - service: notify.supervisor_telegram
    data:
      message: "\U0001F916 Automation - Elian has left the house."
  mode: single
- id: '1675577604748'
  alias: Supervisor - qBitTorrent is Offline
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.uptimekuma_qbittorrent
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: notify.supervisor_telegram
    data:
      message: "\U0001F916 Automation - qBitTorrent is Offline!"
  mode: single
- id: '1675954097249'
  alias: Robot Vacuum Started Notification Telegram
  description: ''
  trigger:
  - platform: state
    entity_id:
    - vacuum.mijia_v2_202f_robot_cleaner
    to: cleaning
  condition: []
  action:
  - service: notify.home_assistant_group
    data:
      message: "\U0001F9F9 Vacuum Robot has started!"
  mode: single
- id: '1675955302558'
  alias: Fish Fed Telegram Notification
  trigger:
  - platform: state
    entity_id: switch.hfjh_v2_eadb_fish_tank_2
    attribute: event.4.1
  condition:
  - alias: Check if the switch didn't go from or to unavailable
    condition: template
    value_template: '{{ not ''unavailable'' in [trigger.from_state.state, trigger.to_state.state]
      }}'
  - alias: Check if the values are correct
    condition: template
    value_template: '{{ not (values.value == ''unknown'' and values.timestamp == ''unknown'')
      }}'
  action:
  - alias: Send the message
    service: notify.home_assistant_group
    data:
      message: "{% if values.error %}\n  \U0001F41F ❌ The fishes have not been fed
        at {{ values.timestamp }} ❌\n{% else %}\n  \U0001F41F The fishes have been
        fed {{ values.value }} portions at {{ values.timestamp }}.\n{% endif %}\n"
  variables:
    values: "{% if state_attr('switch.hfjh_v2_eadb_fish_tank_2', 'event.4.1') is not
      none %}\n  {% set value = (state_attr('switch.hfjh_v2_eadb_fish_tank_2', 'event.4.1')
      | from_json).value[0].value.split(',') %}\n  {% set timestamp = (state_attr('switch.hfjh_v2_eadb_fish_tank_2',
      'event.4.1') | from_json).timestamp %}\n{% endif %} {% set timestamp =  timestamp
      | default() | timestamp_custom('%H:%M %A', default='unknown') %} {% set value
      = (value | default())[6] | default('unknown') %} {% set error = (value | default())[5]
      | default() == 0 %} {{ dict(timestamp=timestamp,value=value,error=error) }}\n"
  mode: single
- id: '1675957403629'
  alias: Robot Vacuum Finished Notification Telegram
  description: ''
  trigger:
  - platform: state
    entity_id:
    - vacuum.mijia_v2_202f_robot_cleaner
    to: returning
  condition: []
  action:
  - service: notify.home_assistant_group
    data:
      title: "\U0001F9F9 Vacuum Robot has finished and returning to base!"
      message: It took {{state_attr('vacuum.mijia_v2_202f_robot_cleaner', 'clean_record.clean_time')}}
        minutes and covered {{ states('sensor.vacuum_clean_area') }} m².
  mode: single
- id: '1676503252475'
  alias: Hallway Motion Light
  description: between 00:01 to 6:35 light will turn on for 2 minutes in the hallway
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_sensor_occupancy
    to: 'on'
    id: Motion Detected on Dining Table by Person
  - platform: state
    entity_id:
    - binary_sensor.motion_sensor_occupancy
    to: 'off'
    for:
      hours: 0
      minutes: 1
      seconds: 40
  condition:
  - condition: time
    after: 00:00:00
    before: 06:36:00
  action:
  - if:
    - condition: trigger
      id: Motion Detected on Dining Table by Person
    - condition: time
      after: 00:01:00
      before: 06:35:00
    then:
    - condition: state
      entity_id: light.xiaomi_yeelink
      state: 'off'
    - service: light.turn_on
      data: {}
      target:
        device_id: 3e6f5b46bee6ed340dcbc9c7419e4e10
    - service: notify.supervisor_telegram
      data:
        message: "\U0001F916 Automation - Hallway Motion Light"
    else:
    - service: light.turn_off
      data:
        transition: 20
      target:
        device_id: 3e6f5b46bee6ed340dcbc9c7419e4e10
  mode: single
- id: '1676677991115'
  alias: Notify with camera snapshot when motion is detected and both of you are not
    home
  description: When Elian & Ofir are not home and motion detected person
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.dining_table_person
    to: 'on'
    from: 'off'
  condition:
  - condition: and
    conditions:
    - condition: device
      device_id: 11337776bbc7cb4d561c95d059379b78
      domain: device_tracker
      entity_id: device_tracker.ofir_phone
      type: is_not_home
    - condition: device
      device_id: 611a494457823cb15ab854ae5b741ef0
      domain: device_tracker
      entity_id: device_tracker.elians_iphone
      type: is_not_home
  action:
  - service: camera.snapshot
    data:
      filename: /config/www/tmp/snapshot_living_room_sub.jpg
    target:
      entity_id: camera.living_room_sub
  - service: telegram_bot.send_photo
    data:
      authentication: digest
      file: /config/www/tmp/snapshot_living_room_sub.jpg
      caption: "\U0001F916 Automation - Notify with camera snapshot when motion is
        detected"
  mode: single
- id: '1677017796757'
  alias: When Ofir Home and Door is open Blink Red Light Strip RGB
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.main_door_sensor_contact
    to: 'on'
  condition:
  - condition: device
    device_id: 11337776bbc7cb4d561c95d059379b78
    domain: device_tracker
    entity_id: device_tracker.ofir_phone
    type: is_home
  - condition: time
    after: '18:30:00'
    before: 02:30:00
  - condition: template
    value_template: '{{ now().timestamp() - as_timestamp(states(''sensor.ofir_pc_lastactive''))
      < 300 }}'
    alias: Has Ofir PC was active in the last 10 minutes ?
  action:
  - service: scene.create
    data:
      scene_id: thebeforetimes
      snapshot_entities: light.office_desk_led_strip
  - repeat:
      count: '76'
      sequence:
      - service: light.toggle
        data:
          color_name: red
        target:
          entity_id: light.office_desk_led_strip
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 250
  - service: scene.turn_on
    target:
      entity_id: scene.thebeforetimes
    metadata: {}
  - service: notify.supervisor_telegram
    data:
      message: "\U0001F916 Automation - Door Open Light Strip Office Flash Red Color"
  mode: single
