- id: '1672002805360'
  alias: Zone Notification
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      notify_device: 11337776bbc7cb4d561c95d059379b78
      person_entity: person.elian
      zone_entity: zone.home
- id: '1672140546661'
  alias: GitHub Push
  description: Everyday in 4AM will update the github.
  trigger:
  - platform: time
    at: 04:00:00
  condition: []
  action:
  - service: shell_command.pushupdates_to_github
    data: {}
  mode: single
- &id001
  id: '1672248739829'
  alias: Laundry Machine Notification
  description: ''
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.laundry_machine_power
      actions:
      - service: notify.mobile_app_elians_iphone
        data:
          message: Laundry Machine has finished!
      - service: notify.mobile_app_ofir_phone
        data:
          message: Laundry machine has finished!
      starting_threshold: 35
      pre_actions:
      - service: notify.notify
        data:
          message: Laundry machine has started!
      starting_hysteresis: 1
- id: '1672416137952'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      time: '19:00:00'
      exclude:
        entity_id: []
        device_id:
        - 611a494457823cb15ab854ae5b741ef0
        - fc87ec384064e20b6a7049f417bf9869
        - 11337776bbc7cb4d561c95d059379b78
        - 611a494457823cb15ab854ae5b741ef0
      actions:
      - service: notify.mobile_app_ofir_phone
        data:
          message: '{{sensors}} has low on battery., please replace it.'
- *id001
- id: '1672558313040'
  alias: Laundry Machine has started
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.laundry_machine_power
    for:
      hours: 0
      minutes: 0
      seconds: 12
    above: 10
  condition:
  - condition: state
    entity_id: input_select.washing_machine_status
    state: 'Off'
  action:
  - service: notify.notify
    data:
      message: "\U0001F49A Laundry Machine has started "
  - service: input_select.select_option
    data:
      option: 'On'
    target:
      entity_id: input_select.washing_machine_status
  mode: single
- id: '1672558877974'
  alias: Laundry machine has finished
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.laundry_machine_power
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: 5
  condition:
  - condition: state
    entity_id: input_select.washing_machine_status
    state: 'On'
  action:
  - service: notify.notify
    data:
      message: "\U0001F456 Laundry machine has finished!"
  - service: input_select.select_option
    data:
      option: 'Off'
    target:
      entity_id: input_select.washing_machine_status
  mode: single
- id: '1672597703705'
  alias: Water Leakage Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak_sensor_water_leak
    - binary_sensor.water_leak_sensor2_water_leak
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.notify
    data:
      message: ⚠️ Water Leak has been detected ⚠️
  mode: single
