- id: '1672002805360'
  alias: Zone Notification
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      notify_device: 11337776bbc7cb4d561c95d059379b78
      person_entity: person.elian
      zone_entity: zone.home
- id: '1672140546661'
  alias: GitHub Push
  description: Everyday in 4AM will update the github.
  trigger:
  - platform: time
    at: 04:00:00
  condition: []
  action:
  - service: shell_command.pushupdates_to_github
    data: {}
  mode: single
- id: '1672416137952'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      time: '19:00:00'
      exclude:
        entity_id:
        - sensor.elians_iphone_battery_state_2
        device_id:
        - 611a494457823cb15ab854ae5b741ef0
        - fc87ec384064e20b6a7049f417bf9869
        - 11337776bbc7cb4d561c95d059379b78
        - 611a494457823cb15ab854ae5b741ef0
      actions:
      - service: notify.mobile_app_ofir_phone
        data:
          message: '{{sensors}} has low on battery., please replace it.'
- id: '1672558313040'
  alias: Laundry Machine has started
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.laundry_machine_power
    for:
      hours: 0
      minutes: 0
      seconds: 12
    above: 10
  condition:
  - condition: state
    entity_id: input_select.washing_machine_status
    state: 'Off'
  action:
  - service: notify.notify
    data:
      message: "\U0001F49A Laundry Machine has started "
  - service: input_select.select_option
    data:
      option: 'On'
    target:
      entity_id: input_select.washing_machine_status
  mode: single
- id: '1672558877974'
  alias: Laundry machine has finished
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.laundry_machine_power
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: 5
  condition:
  - condition: state
    entity_id: input_select.washing_machine_status
    state: 'On'
  action:
  - service: notify.notify
    data:
      message: "\U0001F456 Laundry machine has finished!"
  - service: input_select.select_option
    data:
      option: 'Off'
    target:
      entity_id: input_select.washing_machine_status
  mode: single
- id: '1672597703705'
  alias: Water Leakage Kitchen Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak_sensor_water_leak
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.notify
    data:
      message: ⚠️ Water Leak has been detected in Kitchen ⚠️
  mode: single
- alias: Listen Radio
  trigger:
  - platform: state
    entity_id: input_select.radio_station
  action:
  - service: script.radio
  id: 21c6ee4a48b14f26b12118d4302aaeee
- alias: Set Chromecast Radio Volume
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: '{% if is_state("input_select.chromecast_radio", "Office room") %}
        media_player.ofir_s_echo_dot {% elif is_state("input_select.chromecast_radio",
        "Bedroom") %} media_player.ofir_s_2nd_echo_dot {% endif %}

        '
      volume_level: '{{  states.input_number.volume_radio.state  }}'
  id: c85ea318fb9b4016886a6351309b4d6c
- id: '1672688044345'
  alias: Water Leakage Bathroom Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak_sensor2_water_leak
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.notify
    data:
      message: ⚠️ Water Leak has been detected in Bathroom ⚠️
  mode: single
- id: '1672692110951'
  alias: Switcher Boiler On Notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.switcher_v4_yair_stern_power_consumption
    for:
      hours: 0
      minutes: 0
      seconds: 35
    above: 5
  condition:
  - condition: state
    entity_id: input_select.switcher_boiler_status
    state: 'Off'
  action:
  - service: notify.notify
    data:
      message: "\U0001F6BF Switcher device has been turned ON "
  - service: input_select.select_option
    data:
      option: 'On'
    target:
      entity_id: input_select.switcher_boiler_status
  - service: notify.alexa_media_everywhere
    data:
      message: The DUDE IS ON
  mode: single
- id: '1672692174596'
  alias: Switcher Boiler Off Notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.switcher_v4_yair_stern_power_consumption
    for:
      hours: 0
      minutes: 2
      seconds: 0
    below: 5
  condition:
  - condition: state
    entity_id: input_select.switcher_boiler_status
    state: 'On'
  action:
  - service: notify.notify
    data:
      message: "\U0001F6BF Switcher device has been turned OFF"
  - service: input_select.select_option
    data:
      option: 'Off'
    target:
      entity_id: input_select.switcher_boiler_status
  - if:
    - condition: template
      value_template: '{{ states(''sensor.time'') | int < 1 or states(''sensor.time'')
        | int > 7 }}'
    then:
    - service: notify.alexa_media_everywhere
      data:
        message: The DUDE IS OFF
  mode: single
- id: '1672863829342'
  alias: Sensor Light
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.motion_sensor_occupancy
      light_switch:
        entity_id: light.xiaomi_yeelink
      end_scenes: []
      time_delay: 1.5
      include_bypass: bypass_disabled
      ambient_light_options: ambient_light_option_disabled
      include_ambient: ambient_disabled
      include_time: time_enabled
      after_time: 01:00:00
      before_time: 07:00:00
      include_sun: sun_disabled
