# [=========================]Phones at home[=========================]
- platform: template
  sensors:
    any_phone_at_home:
      value_template: "{{ is_state('device_tracker.elians_iphone', 'home') or is_state('device_tracker.ofir_honor_magic_5_pro', 'home') }}"
      device_class: presence
# [=========================]Phones at home[=========================]
