# Loads default set of integrations. Do not remove.
default_config:

# [=========================]Xiaomi Miot[=========================]
xiaomi_miot:
  # https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/device_customizes.py
  device_customizes:
    chuangmi.plug.212a01:
      miot_local: true
      chunk_properties: 7
  exclude_state_attributes:
    - miot_type
    - stream_address
    - motion_video_latest
# [=========================]Xiaomi Miot[=========================]
rest_command:
  switchbot_device_command:
    url: "https://api.switch-bot.com/v1.0/devices/{{ deviceId }}/commands"
    method: post
    content_type: "application/json"
    headers:
      Authorization: !secret switchbot_api
    payload: '{"command": "{{ command }}"}'

switch:
  - platform: template
    switches:
      tv_office:
        friendly_name: Office TV
        turn_on:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_deviceId
            command: "turnOn"
        turn_off:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_deviceId
            command: "turnOff"
        icon_template: >-
          {% if is_state('switch.tv_office', 'off') %}
            mdi:television
          {% else %}
            mdi:television
          {% endif %}
# [=========================]Spotcast[=========================]
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
# [=========================]Spotcast[=========================]
logbook:
  exclude:
    entities:
      - sensor.time

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
# [=========================]Glances[=========================]
glances:
  - host: 10.0.0.151
# [=========================]Glances[=========================]
# [=========================]trakt.tv[=========================]
trakt_tv:
  language: en
  timezone: Europe/Paris
  sensors:
    upcoming:
      show:
        days_to_fetch: 30
        max_medias: 10
      movie:
        days_to_fetch: 45
        max_medias: 5
    recommendation:
      show:
        max_medias: 3
      movie:
        max_medias: 3
# [=========================]trakt.tv[=========================]
# [=========================]Authenticated[=========================]
logger:
  default: info
  logs:
    custom_components.authenticated: debug
# [=========================]Authenticated[=========================]
# [=========================]Themes[=========================]
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
# [=========================]Themes[=========================]

# [=========================]Text to speech[=========================]
tts:
  - platform: google_translate
# [=========================]Text to speech[=========================]

automation: !include automations.yaml
script: !include scripts.yaml
input_select: !include input_select.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
template: !include templates.yaml

homeassistant:
  customize: !include customize.yaml

shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh
