# Loads default set of integrations. Do not remove.
default_config:

# [=========================]Xiaomi Miot[=========================]
xiaomi_miot:
  # https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/device_customizes.py
  device_customizes:
    chuangmi.plug.212a01:
      miot_local: true
      chunk_properties: 7
  exclude_state_attributes:
    - miot_type
    - stream_address
    - motion_video_latest
# [=========================]Xiaomi Miot[=========================]
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.time
recorder:
  exclude:
    entities:
      - sensor.date
      - sensor.date_time

# [=========================]Sensibo Sensor[=========================]
template:
  - sensor:
      - name: Sensibo_Humidity
        state: "{{ state_attr('climate.ofir_a_c', 'current_humidity') }}"
        unit_of_measurement: "%"
        icon: mdi:water-percent
# [=========================]Sensibo Sensor[=========================]
# [=========================]Camera's[=========================]
camera:
  - platform: generic
    name: Yair Stern 22 - Bedroom & Kitchen Camera
    still_image_url: http://192.xxxxxxx/jpg/image.jpg
    stream_source: rtsp://192.xxxxxxx:554/11

  - platform: generic
    name: Yair Stern 22 - Main Door Camera
    still_image_url: http://192.xxxxxxxx/jpg/image.jpg
    stream_source: rtsp://192.xxxxxxxx.44:554/11

# [=========================]Camera's[=========================]

# [=========================]Authenticated[=========================]
logger:
  default: info
  logs:
    custom_components.authenticated: debug
# [=========================]Authenticated[=========================]

# [=========================]Themes[=========================]
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js

# [=========================]Themes[=========================]

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# [=========================]Text to speech[=========================]
tts:
  - platform: google_translate
# [=========================]Text to speech[=========================]

automation: !include automations.yaml
script: !include scripts.yaml
input_select: !include input_select.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
group: !include groups.yaml

homeassistant:
  customize: !include customize.yaml

shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh
