# Loads default set of integrations. Do not remove.
default_config:
# [=========================]Spotcast[=========================]
spotcast:
  sp_dc: !secret primary_sp_dc
  sp_key: !secret primary_sp_key
  country: IL #optional, added in 3.6.24

# [=========================]Spotcast[=========================]
logbook:
  exclude:
    entities:
      - sensor.time
# [=========================]Alexa[=========================]
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
# [=========================]Alexa[=========================]
# [=========================]trakt.tv[=========================]
trakt_tv:
  language: en
  timezone: Europe/Paris
  sensors:
    upcoming:
      show:
        days_to_fetch: 30
        max_medias: 10
      movie:
        days_to_fetch: 45
        max_medias: 5
    recommendation:
      show:
        max_medias: 3
      movie:
        max_medias: 3
# [=========================]trakt.tv[=========================]
# [=========================]Authenticated[=========================]
logger:
  default: info
  logs:
    custom_components.authenticated: debug
# [=========================]Authenticated[=========================]
# [=========================]Themes[=========================]
frontend: !include themes.yaml

lovelace:
  mode: yaml
  resources: [
      { url: "/hacsfiles/apexcharts-card/apexcharts-card.js", type: module },
      { url: "/hacsfiles/bar-card/bar-card.js", type: module },
      { url: "/hacsfiles/button-card/button-card.js", type: module },
      { url: "/hacsfiles/vacuum-card/vacuum-card.js", type: module },
      { url: "/hacsfiles/kiosk-mode/kiosk-mode.js", type: module },
      { url: "/hacsfiles/stack-in-card/stack-in-card.js", type: module }, # Lock button
      {
        url: "/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js",
        type: module,
      },
      { url: "/hacsfiles/room-card/room-card.js", type: module }, # Mobile Dashboard Cards
      {
        url: "/hacsfiles/mini-climate-card/mini-climate-card-bundle.js",
        type: module,
      }, # Mobile Cards
      { url: "/hacsfiles/lovelace-layout-card/layout-card.js", type: module }, # Grid Layout - Tablet Dashboard
      {
        url: "/hacsfiles/lovelace-more-info-card/more-info-card.js",
        type: module,
      },
      { url: "/hacsfiles/lovelace-mushroom/mushroom.js", type: module },
      {
        url: "/hacsfiles/lovelace-slider-entity-row/slider-entity-row.js",
        type: module,
      },
      { url: "/hacsfiles/swipe-card/swipe-card.js", type: module },
      { url: "/hacsfiles/tabbed-card/tabbed-card.js", type: module },
      {
        url: "/hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js",
        type: module,
      },
      { url: "/hacsfiles/spotify-card/spotify-card.js", type: module },
      {
        url: "/hacsfiles/mini-media-player/mini-media-player-bundle.js",
        type: module,
      },
      {
        url: "/hacsfiles/upcoming-media-card/upcoming-media-card.js",
        type: module,
      },
      {
        url: "/hacsfiles/mini-graph-card/mini-graph-card-bundle.js",
        type: module,
      },
      {
        url: "/hacsfiles/light-entity-card/light-entity-card.js",
        type: module,
      }, #Mobile Dashboard
      {
        url: "/hacsfiles/calendar-card-pro/calendar-card-pro.js",
        type: module,
      }, #Calendar Pro
      { url: "/hacsfiles/Bubble-Card/bubble-card.js", type: module }, #Bubble Card for Doorbell photo
      { url: "/local/marked.min.js?v=4.2.1", type: module }, #Tablet Dashboard
      { url: "/local/vanilla-tilt.min.js?v=1.7.3", type: module }, #Tablet Dashboard
      { url: "/local/browser_mod_icon.js?v=0.5", type: module }, #Tablet Dashboard
      { url: "/local/fonts.css?v=2.1", type: css }, #Tablet Dashboard
    ]
# [=========================]Themes[=========================]

# [=========================]Text to speech[=========================]
tts:
  - platform: google_translate
# [=========================]Text to speech[=========================]

automation: !include automations.yaml
script: !include scripts.yaml
input_select: !include input_select.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
template: !include templates.yaml

homeassistant:
  packages: !include_dir_named packages
shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh
  legacy_action_sensor: true

# [=========================]Ombi[=========================]
ombi:
  host: "10.0.0.153"
  username: !secret ombi_user
  api_key: !secret ombi_api
  port: 3579
# [=========================]Ombi[=========================]
# [=========================]Home Zone[=========================]
zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 42
    icon: mdi:account-multiple
# [=========================]Home Zone[=========================]
# [=========================]Telegram[=========================]
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegramSupervisor_groupChatId
      - !secret telegram_groupChatId

notify:
  - platform: telegram
    name: Home Assistant Group
    chat_id: !secret telegram_groupChatId
  - platform: telegram
    name: Supervisor Telegram
    chat_id: !secret telegramSupervisor_groupChatId
  - name: WhatsApp
    platform: rest
    resource: https://api.callmebot.com/whatsapp.php
    data:
      source: HA
      phone: !secret whatsapp_PhoneNum
      apikey: !secret whatsapp_ApiKey
# [=========================]Telegram[=========================]
