# Loads default set of integrations. Do not remove.
default_config:

# [=========================]Xiaomi Miot[=========================]
xiaomi_miot:
  # https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/device_customizes.py
  device_customizes:
    chuangmi.plug.212a01:
      miot_local: true
      chunk_properties: 7
  exclude_state_attributes:
    - miot_type
    - stream_address
    - motion_video_latest
# [=========================]Xiaomi Miot[=========================]
# [=========================]Sensibo Sensor[=========================]
template:
  - sensor:
      - name: Sensibo_Humidity
        state: "{{ state_attr('climate.ofir_a_c', 'current_humidity') }}"
        unit_of_measurement: "%"
        icon: mdi:water-percent
# [=========================]Sensibo Sensor[=========================]
# [=========================]Input Select[=========================]
input_select:
  chromecast_tv:
    name: Chromecast Devices
    options:
      - media_player.mibox4
      - media_player.mibox4_2
      - media_player.mecool_ofir
    initial: media_player.mecool_ofir
    icon: mdi:cast-connected
  camera_select:
    options:
      - camera.chuangmi_ipc016_b764_camera_control
      - camera.chuangmi_ipc016_e927_camera_control
      - camera.chuangmi_ipc016_e7fb_camera_control
# [=========================]Input Select[=========================]

# [=========================]System Monitor[=========================]
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_free
      - type: processor_use
      - type: memory_use_percent
  - platform: authenticated

  # Time
  - platform: time_date
    display_options:
      - "time"

  # Count Number Of Automations
  - platform: template
    sensors:
      count_automations:
        friendly_name: "Count Of Automations"
        value_template: >-
          {{ states.automation | list | count }}
  # Count Number Of Binary Sensors
  - platform: template
    sensors:
      count_binary_sensor:
        friendly_name: "Count Of Binary Sensors"
        value_template: >-
          {{ states.binary_sensor | list | count }}
  # Count Number Of Covers
  - platform: template
    sensors:
      count_covers:
        friendly_name: "Count Of Cover (Doors)"
        value_template: >-
          {{ states.cover | list | count }}
  # Count Number Of Device Trackers
  - platform: template
    sensors:
      count_device_trackers:
        friendly_name: "Count Of Device Trackers"
        value_template: >-
          {{ states.device_tracker | list | count }}
  # Count Number Of Entities
  - platform: template
    sensors:
      count_entities:
        friendly_name: "Count Of Entities"
        value_template: >
          {{ states | length }}
  # Count Number Of Groups
  - platform: template
    sensors:
      count_groups:
        friendly_name: "Count Of Groups"
        value_template: >-
          {{ states.group | list | count }}
  # Count Number Of Input Numbers
  - platform: template
    sensors:
      count_input_numbers:
        friendly_name: "Count Of Input Numbers"
        value_template: >-
          {{ states.input_number | list | count }}
  # Count Number Of Input Select
  - platform: template
    sensors:
      count_input_selects:
        friendly_name: "Count Of Input Selects"
        value_template: >-
          {{ states.input_select | list | count }}
  # Count Number Of Input Text
  - platform: template
    sensors:
      count_input_texts:
        friendly_name: "Count Of Input Texts"
        value_template: >-
          {{ states.input_text | list | count }}
  # Count Number Of Lights
  - platform: template
    sensors:
      count_lights:
        friendly_name: "Count Of Lights"
        value_template: >-
          {{ states.light | list | count }}
  # Count Number Of Media Players
  - platform: template
    sensors:
      count_media_players:
        friendly_name: "Count Of Media Players"
        value_template: >-
          {{ states.media_player | list | count }}
  # Count Number Of Persons
  - platform: template
    sensors:
      count_persons:
        friendly_name: "Count Of Persons"
        value_template: >-
          {{ states.person | list | count }}
  # Count Number Of Scripts
  - platform: template
    sensors:
      count_scripts:
        friendly_name: "Count Of Scripts"
        value_template: >-
          {{ states.script | list | count }}
  # Count Number Of Sensors
  - platform: template
    sensors:
      count_sensor:
        friendly_name: "Count Of Sensors"
        value_template: >-
          {{ states.sensor | list | count }}
  # Count Number Of Switches
  - platform: template
    sensors:
      count_switches:
        friendly_name: "Count Of Switches"
        value_template: >-
          {{ states.switch | list | count }}
  # Count Number Of Timers
  - platform: template
    sensors:
      count_timers:
        friendly_name: "Count Of Timers"
        value_template: >-
          {{ states.timer | list | count }}
  # Count YAML Files
  - platform: command_line
    name: "Count YAML Files"
    command: " find /config/ -name '*.yaml' | wc -l"
  # Count YAML Lines
  - platform: command_line
    name: "Count YAML Lines"
    command: " find /config/ -name '*.yaml' | xargs cat | wc -l"
  # Count Number Of Zones
  - platform: template
    sensors:
      count_zones:
        friendly_name: "Count Of Zones"
        value_template: >-
          {{ states.zone | list | count }}
# [=========================]System Monitor[=========================]
# [=========================]Authenticated[=========================]
logger:
  default: info
  logs:
    custom_components.authenticated: debug
# [=========================]Authenticated[=========================]

# [=========================]Themes[=========================]
frontend:
  themes: !include_dir_merge_named themes

# [=========================]Themes[=========================]

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# [=========================]Text to speech[=========================]
tts:
  - platform: google_translate
# [=========================]Text to speech[=========================]

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml

shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh
