# Time
- platform: time_date
  display_options:
    - time
    - date
# [=========================]Plex[=========================]
- platform: plex_recently_added
  name: Recently Added Movies # will create sensor.recently_added_movies
  token: !secret plex_token
  host: !secret plex_host
  port: 32400
  section_types:
    - movie

- platform: plex_recently_added
  name: Recently Added TV # will create sensor.recently_added_tv
  token: !secret plex_token
  host: !secret plex_host
  port: 32400
  section_types:
    - show

- platform: plex_recently_added
  name: Recently Added TV # will create sensor.recently_added
  token: !secret plex_token
  host: !secret plex_host
  port: 32400
# [=========================]Plex[=========================]
# [=========================]qBitTorrent[=========================]
- platform: template
  sensors:
    bytes_sent:
      friendly_name: "MB Sent"
      unit_of_measurement: "MB/s"
      value_template: "{{ (states('sensor.qbittorrent_down_speed') | int / 1000) | round(1) }}"
      availability_template: "{{ states('sensor.qbittorrent_down_speed')|is_number }}"
    bytes_upload:
      friendly_name: "MB Sent"
      unit_of_measurement: "MB/s"
      value_template: "{{ (states('sensor.qbittorrent_up_speed') | int / 1000) | round(1) }}"
      availability_template: "{{ states('sensor.qbittorrent_down_speed')|is_number }}"
# [=========================]qBitTorrent[=========================]
