homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt_user
  password: mqtt1234
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xa4c138058812e73e':
    friendly_name: Bedroom Wireless Remote Switch
  '0xa4c13870da020238':
    friendly_name: Laundry Machine
    description: Smart Switch EU
  '0x70ac08fffe22f51e':
    friendly_name: Smart IR Remote Control
  '0xa4c1383422d28f86':
    friendly_name: Bedroom Temperature Sensor
    description: Temp - located next to the plugs, behind the TV.
  '0x00158d0008e0195a':
    friendly_name: Water Leak Shower Sink
    description: Sensor - Water Leak Shower Sink under the shower sink
  '0xa4c138cf6f460fd1':
    friendly_name: Bedroom AC
    description: Smart Switch EU
  '0xa4c1387bf0a99185':
    friendly_name: Office Temperature Sensor
    description: Temp - On top of the 'Game On' photo frame.
  '0xa4c13838ba9b0045':
    friendly_name: Wardrobe Temperature Sensor
    description: Temp - located on top of the closet.
  '0xa4c13852cfb738a6':
    friendly_name: Bathroom Temperature Sensor
    description: Temp - located on top of fan.
  '0x943469fffef84a59':
    friendly_name: Bedroom Smart IR Remote Control
  '0x00158d0006f84b67':
    friendly_name: Office desk button
    description: Under the gaming table, right side
    legacy: false
  '0xa4c138dc96ec297c':
    friendly_name: Main Door Sensor
    description: Top of Main Door Entrance
  '0x00158d0008dff275':
    friendly_name: Water Leak Sensor Kitchen Sink
  '0x84fd27fffe600604':
    friendly_name: Office Elian Desk RGB Strip
    description: all over Elian's desk
  '0xa4c13825cb23672c':
    friendly_name: Bedroom TV
  '0xa4c138c861145739':
    friendly_name: Heater Shower
    description: Heater - located above the power plugs.
  '0xa4c138e832f03f77':
    friendly_name: Bedroom Door Sensor
  '0xa4c1389c053df036':
    friendly_name: Office TV
  '0xa4c13849a2e5e351':
    friendly_name: Living Room TV
  '0x00158d00076b15f3':
    friendly_name: Bedroom Sticker Switch button
    description: Under the table next to the bed
  '0xa4c1383a2646aef0':
    friendly_name: Office Presence Sensor
    description: Presence Sensor - located in Office room, next to the side window.
  '0xa4c13822c402f4e9':
    friendly_name: Boiler
    description: Boiler - located next to shower door, in the wall.
  '0xa4c138a84422458a':
    friendly_name: Office Wall Light
    description: Light - located next to shower/bathroom door in office, on the wall.
  '0x00158d000a9c73de':
    friendly_name: Water Leak Office Sink
    description: Sensor - Water Leak Office Shower Sink under the sink.
  '0xa4c1384fd1d8ba32':
    friendly_name: Living Room Wireless Remote Switch
  '0xa4c13811ce44a42b':
    friendly_name: Wardrobe Wireless Remote Switch
  '0x54ef4410007588b8':
    friendly_name: Kitchen Presence Sensor
    description: Presence - located above the kitchen cabinet, next to the reolink camera
  '0x70ac08fffe5aa806':
    friendly_name: Kitchen Smoke Detector
    description: Smoke Detector - located above the gas, on the celling.
  '0x00158d000a9747d1':
    friendly_name: Living Room Left Window
    description: on the left window blinds
  '0x00158d000a95e833':
    friendly_name: Living Room Right Window
    description: on the right window blinds
  '0xa4c138621f5ece9d':
    friendly_name: Office Ofir Desk RGB Strip
    description: all over Ofir Desk.
  '0xf082c0fffe89fdaf':
    friendly_name: Wardrobe Zigbee Extender
    description: Extender - located under the AC
  '0x040d84fffebdf9a6':
    friendly_name: Living Room Zigbee Extender
    description: Extender - located under the AC
  '0xa4c1380973dca97e':
    friendly_name: Bathroom Presence Sensor
    description: Presence - located on the fan [top of the celling]
  '0xa4c1385f2de174b5':
    friendly_name: Bedroom Motion Sensor
    description: Motion Sensor - located next to Ofir bed side.
  '0xf4b3b1fffea0bae7':
    friendly_name: Bathroom Motion Sensor
