homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt_user
  password: mqtt1234
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xa4c138058812e73e':
    friendly_name: Wireless Remote Switch
  '0xa4c13870da020238':
    friendly_name: Laundry Machine
    description: Smart Switch EU
  '0x70ac08fffe22f51e':
    friendly_name: Smart IR Remote Control
  '0x00158d0008dff275':
    friendly_name: Water Leak Sensor
  '0xa4c1383422d28f86':
    friendly_name: Temperature & Humidity Sensor
  '0x00158d0008e0195a':
    friendly_name: Water Leak Sensor2
    description: Bathroom
  '0xa4c138a831c3931c':
    friendly_name: Motion Sensor
