homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt_user
  password: mqtt1234
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xa4c138058812e73e':
    friendly_name: Wireless Remote Switch
  '0xa4c13870da020238':
    friendly_name: Laundry Machine
    description: Smart Switch EU
  '0x70ac08fffe22f51e':
    friendly_name: Smart IR Remote Control
  '0xa4c1383422d28f86':
    friendly_name: Bedroom Temperature Sensor
  '0x00158d0008e0195a':
    friendly_name: Water Leak Sensor Bathroom Sink
    description: Bathroom
  '0xa4c138cf6f460fd1':
    friendly_name: AC Bedroom
    description: Smart Switch EU
  '0xa4c1387bf0a99185':
    friendly_name: Office Temperature Sensor
    description: Next to the camera on top of the wall
  '0xa4c13838ba9b0045':
    friendly_name: Hallway Temperature Sensor
  '0xa4c13852cfb738a6':
    friendly_name: Bathroom Temperature Sensor
  '0x943469fffef84a59':
    friendly_name: Bedroom Smart IR Remote Control
  '0xa4c138211ff1b449':
    friendly_name: Living Room Light Module
    description: Inside the wall - living room switch
  '0x00158d0006f84b67':
    friendly_name: Hallway Sticker Switch button
    description: Hallway above switches
    legacy: false
  '0xa4c138dc96ec297c':
    friendly_name: Main Door Sensor
    description: Top of Main Door Entrance
  '0x00158d0008dff275':
    friendly_name: Water Leak Sensor Kitchen Sink
  '0x84fd27fffe600604':
    friendly_name: Office Desk LED Strip
  '0xa4c13825cb23672c':
    friendly_name: 'TV Bedroom '
  '0xa4c138c861145739':
    friendly_name: Heater Bathroom
  '0xa4c138e832f03f77':
    friendly_name: Bedroom Door Sensor
  '0xa4c1389c053df036':
    friendly_name: Office TV
  '0xa4c13849a2e5e351':
    friendly_name: Living Room TV
  '0x00158d00076b15f3':
    friendly_name: Bedroom Sticker Switch button
    description: Under the table next to the bed
  '0xa4c1383a2646aef0':
    friendly_name: Presence Sensor
    description: Office
  '0x00158d0006c8f369':
    friendly_name: '0x00158d0006c8f369'
